### ISSUE TITLE
link expired

### ISSUE THREAD

**Issue by mrqy0610** [bic4907/Overcooked-AI#3]
Hello, thanks for your work.
However I found that your link to your data has been expired, could you please update the link for dataset?thank you.

**Comment by bic4907** [comment]
The link was expired so you cannot download the data with those link anymore.
Instead, I add the files and update the on the repository.

Please pull the repository again and go to the path on the below and try to unzip the files.

[https://github.com/bic4907/Overcooked-AI/tree/main/result/pre-collected](https://github.com/bic4907/Overcooked-AI/tree/main/result/pre-collected)

Cheers!
